### ISSUE TITLE
homepage layout don't support mobile browser

### ISSUE THREAD

**Issue by cntrump** [josephhutch/aether#13]
iphone 8 plus, iOS 12 safari
my site: https://lvv.me

![](https://github.com/cntrump/pics/raw/master/aether/homepage.jpg)

**Comment by josephhutch** [comment]
Your third card has text that is longer than the width of the screen.  I'll investigate a fix tomorrow as it is getting late here.

**Comment by cntrump** [comment]
> @cntrump, fixed with commit [59b3abd](https://github.com/josephhutch/aether/commit/59b3abd760734132d5602351c1ac06aea444d93a)

It works! thanks very much!
