### ISSUE TITLE
img/grey-cloud.jpg is too big

### ISSUE THREAD

**Issue by cntrump** [josephhutch/aether#15]
It is neccesary? load slowly... sad...

**Comment by josephhutch** [comment]
Yea, I need to crop and compress that image.  If you do it yourself, submit a pull request 👍🏼

**Comment by cntrump** [comment]
> @cntrump, I cropped and compressed the image [c7cd51c](https://github.com/josephhutch/aether/commit/c7cd51c667243102d064878d9eba2bd06ba71097). It is much smaller now but still big enough that it will look good on high resolution screens.

After crop, 1920x495 is still too big, I think you can try reduce width or let user custom in config.

**Comment by josephhutch** [comment]
@cntrump, you can customize the 'homeimg' in the config file.  I can crop the photo down to 1200x400  but I don't want to go any smaller because of high resolution displays (4k/5k)
