### ISSUE TITLE
Best practice for page bundle image paths in smallimg?

### ISSUE THREAD

**Issue by leason** [josephhutch/aether#20]
Love the theme - many thanks for sharing it.  What's the best way to reference a page bundle image in a post?

Given this structure:
```
content/
  posts/
     article1/
       headshot.png
       index.md
```
What should the src of a <smallimg> in index.md be?

**Comment by josephhutch** [comment]
I'm glad you like the theme! You would reference the image like this

`src="posts/article1/headshot.png"`

The `src` property is a root-relative link.  Let me know if you have any other questions :)

**Comment by leason** [comment]
Got it, that works great.  Many thanks.
