### ISSUE TITLE
How to enable RSS feed support

### ISSUE THREAD

**Issue by leason** [josephhutch/aether#23]
It looks like there is built in support for RSS in Hugo but I can't figure out how to enable it.  Is that a theme level setting?

**Comment by josephhutch** [comment]
RSS is enabled by default.  The theme should generate an index.xml file at the root of you site that will enable RSS readers to scrape your site.  If that isn't working, let me know and I'll investigate

**Comment by leason** [comment]
Ah, just didn't know where to look - thanks!
