### ISSUE TITLE
Image rotation ?

### ISSUE THREAD

**Issue by pabouttier** [josephhutch/aether#31]
I love your great theme, a lot of thanks!

Just a problem on my side: I try to include an (portrait) image in my article (in the body or with the featuredImage parameter. After building, it appears that the image is always rotated (in landscape). Do you have any idea to tackle this issue?

Many thanks again

**Comment by josephhutch** [comment]
I'm unable to reproduce this issue.  Can you provide a link to your site where this is happening?

**Comment by pabouttier** [comment]
Here the website : https://pabouttier.me/posts/amsterdam/
Here the associated repo : https://github.com/pabouttier/pabouttier.github.io

**Comment by josephhutch** [comment]
The theme is not rotating your image, it is displaying the picture in the orientation it is saved in. See [https://pabouttier.me/img/canal_perdu.jpg](https://pabouttier.me/img/canal_perdu.jpg).  You must rotate the image using a photo editing application.
