### ISSUE TITLE
[Feature Request] add featuredImageLink

### ISSUE THREAD

**Issue by gadelkareem** [josephhutch/aether#34]
It would be great if we can add a link to the main featured image sometimes

**Comment by josephhutch** [comment]
Where would you like the link to appear?  I'm assuming you are suggesting making featuredImageLink a front matter parameter.  Can you explain why you wouldn't want to add the link manually?

**Comment by gadelkareem** [comment]
I am actually not sure how to add it manually. Is there a way to add anchor link to the featured image?

**Comment by josephhutch** [comment]
Sorry, I am a little lost.  Can you clarify what you are trying to do?  Are you trying to make the image itself a link, or are you trying to add a text link to the image?

**Comment by gadelkareem** [comment]
I meant something like 
```
< a href="{{featuredImageLinkURL}}"><img src="{{featuredImage}}" /></a>
```
So the image would have a link since it is the first big element on the post.

**Comment by josephhutch** [comment]
What would be the use case for this?

**Comment by gadelkareem** [comment]
I use the feature with Wordpress to display a bigger image like in https://gadelkareem.com/2018/10/23/deploy-a-docker-registry-with-letsencrypt-certificates-on-ubuntu-18-04/ but generally it could be useful to link to another page.

**Comment by josephhutch** [comment]
Thank you for the suggestion but I don't think this would fit in with the simplicity of the theme.  If you have any other feature requests, I'm happy to hear them.
