### ISSUE TITLE
failed to render shortcode "smallimg", featuredImage didn't show up

### ISSUE THREAD

**Issue by skylancers** [josephhutch/aether#36]
when I copy all the files from exampleSite folder this is what happened,
Result:
![Untitled-1](https://user-images.githubusercontent.com/52638665/61759117-992b8300-adf1-11e9-8ff9-38d20dfe5ca0.jpg)
I try this in localhost and Netlify and has the same result.

If I delete aether-features.md site work normally but the featuredImage didn't show up
Result:
![Untitled-2](https://user-images.githubusercontent.com/52638665/61759561-efe58c80-adf2-11e9-9d5a-a101c1637c7f.jpg)

I just want to see the themes work like in your screenshot.

**Comment by josephhutch** [comment]
Sorry, I made changes to the way images work over the weekend but didn't update the example site.  The latest commit fixes these issues.  Let me know if you run into any other issues.

\* One thing to note is that the image and smallimg shortcodes look for the image using the name field.  If you overwrite the image name in the resources section of the front matter, you will need to use the new name in the src field of the image and smallimg shortcodes.  This should only occur when displaying the featuredImage using either of the image shortcodes.

**Comment by skylancers** [comment]
Thank you very much, everything works fine now.
