### ISSUE TITLE
Can't use smallimg shortcode

### ISSUE THREAD

**Issue by kbkesit** [josephhutch/aether#44]
It seems the smallimg shortcode isn't working properly. Does anyone else have the same issue?

**Comment by josephhutch** [comment]
Can you provide an example of this issue in a public repo?  I would like to take a look.

**Comment by josephhutch** [comment]
Hi @kbkesit, I have made some improvements to the `smallimg` shortcode.  Let me know if it is working better for you.

**Comment by josephhutch** [comment]
@kbkesit I have been using the Smallimg shortcake in my site without any issues.  If you are still experiencing an issue, please comment with a description of the problem you are facing.  Closing this issue for now.
