### ISSUE TITLE
cannot use static images for card image

### ISSUE THREAD

**Issue by fwantastic** [josephhutch/aether#45]
I may be missing something of how to configure this properly. It seems like static images cannot be used as a card image anymore. If I revert the changes for `li.html` it works fine. I use the same images for the posts that fall into similar categories so it doesn't make sense for me to have different card images for every posts. Is it possible to add this feature back?

**Comment by josephhutch** [comment]
I updated the theme to use [Page Bundles](https://gohugo.io/content-management/page-bundles/).  With this method you get automated image resizing.  I will investigate a way to still support the static use case.

**Comment by fwantastic** [comment]
cool. thank you! I think aether is one of the great looking theme among others
