### ISSUE TITLE
Workaround for rel="alternate" due to google podcasts rule

### ISSUE THREAD

**Issue by diogodh** [josephhutch/aether#47]
I'm using your theme on my podcast home page. By default, aether creates the following index.html code
`"<link rel="alternate" type="application/rss+xml" href="/index.xml" title="Title" />`

However, google has a rule that to a podcast be indexed it can only have one instance of `<link rel="alternate"` and needs to the the one from google
`<link type="application/rss+xml" rel="alternate" title="Title" href="feed.xml"/>`

My question is how can i hardcode the index.html or even your theme to bypass this situation.

**Comment by josephhutch** [comment]
By default Hugo includes RSS as a default output format.  To remove the the RSS link and to include your podcast's feed.xml see [this docs section](https://gohugo.io/templates/output-formats/#customizing-output-formats).  That whole page on custom output formats should be helpful.

**Comment by josephhutch** [comment]
@diogodh were you able to solve this issue?

**Comment by diogodh** [comment]
Hey Joe.
I am very thankful for your help, but as an amateur programing i found that
section too confusing and I would mess up everything for sure.
Even so, thank u for your help and for trying to figure if i solve it.
Diogo

**Comment by josephhutch** [comment]
Add this to your config.toml file.  The rss link tag will be replaced with your podcast's feed tag.  Notice that you get a warning when building your site with these config changes.  You can add a template for your new `PodcastFeed` output format which will automatically generate the feed.xml file and remove the warning.
```toml
[outputFormats]
  [outputFormats.PodcastFeed]
    baseName = "feed"
    isPlainText = true
    mediaType = "application/rss+xml"

[outputs]
  home = ["HTML", "PodcastFeed"]
```
I can work on adding a podcast template to the theme but I would like some info before I get started.  Where do you store your podcast files?  Posting an example of your feed.xml file would be very helpful.

**Comment by diogodh** [comment]
I will do it as soon as possible.
About my podcast, most podcast providers request a frontpage for the
podcast, and you can see mine here:

http://medicinacomsotaque.com.s3-website-us-east-1.amazonaws.com/

(amazon s3 hosting)

As for the feed.xml its here

http://medicinacomsotaque.com.s3-website-us-east-1.amazonaws.com/pc/feed.xml


As its an hobbie, I am not spending time with the website, instead i spend
providing episodes.

But thank you so much for your help and i will definitely change my source
code to try your suggestion.

Feel free to contact me and if you want me as a beta tester, just say.

**Comment by josephhutch** [comment]
@diogodh any luck with the output formats fix?  I haven't had a chance to implement a PodcastFeed output format but it's on my list.

**Comment by diogodh** [comment]
Hey. I just needed to customize the page so I had to hardcode the html and
now i can't go back to hugo and add that fix otherwise i will lose all that
i coded..

I'm both thankful for your help and sorry for have the need to hardcode the
html.

Maybe if there is a podcast output i will change everything.

thanks

**Comment by josephhutch** [comment]
Okay, I am going to close this issue as I have tested the solution above as a fix for the re="alternate" google podcast rule.

**Comment by diogodh** [comment]
Thank you so much
