### ISSUE TITLE
featured image for a post not working

### ISSUE THREAD

**Issue by ST2-EV** [josephhutch/aether#49]
I added the image to the static folder and gave the filename for source but no change is reflected
![Screenshot from 2020-02-14 14-45-14](https://user-images.githubusercontent.com/40699517/74517730-a8625180-4f38-11ea-821b-000d5dd1ec47.png)

**Comment by josephhutch** [comment]
Aether takes advantage of [page bundles](https://gohugo.io/content-management/page-bundles/) to optimize your images for your site.  This may require you to update the way your content is structured, also see [content organization](https://gohugo.io/content-management/organization/).

For instance, if your webpage is www.joehutch.com/posts/aether-theme/ then the markdown for the page should be written in content/posts/aether-theme/index.md and images should be stored in the content/posts/aether-theme/ folder.

**Comment by ST2-EV** [comment]
thanks for the quick response
just put the image inside the posts folder worked for me
