### ISSUE TITLE
How do ichange the color of certain text, html tags dont seem to work

### ISSUE THREAD

**Issue by ST2-EV** [josephhutch/aether#50]

**Comment by josephhutch** [comment]
Using html tags to change text color does work.  I verified the following example `<p style="color:blue;">Hello World!</p>` works on my site.  To modify the themes css see https://github.com/josephhutch/aether#overriding-css

**Comment by ST2-EV** [comment]
![Screenshot from 2020-02-15 07-38-45](https://user-images.githubusercontent.com/40699517/74580082-55cf7680-4fc6-11ea-8fb0-c9c03b950c3f.png)
I get this when I add that, what could be the problem?

**Comment by ST2-EV** [comment]
Also there is no assets folder in the project root should i make one or is there supposed to be one?
Sorry kind of a noob here!

**Comment by ST2-EV** [comment]
Also, how do I achieve a parallax effect with the bg image,
tried adding this in override.css:
```
body {
  background-repeat: no-repeat;
  background-attachment: fixed;
}


```
it doesn't work
Sorry kind of a noob here

**Comment by josephhutch** [comment]
No worries.  Since the background is actually set in the html, you need to use `!important` as shown below.

```css
body {
    background-attachment: fixed !important;
}
```

**Comment by ST2-EV** [comment]
thanks a lot man
