### ISSUE TITLE
Featured Image without Page Bundles

### ISSUE THREAD

**Issue by sebilozano** [josephhutch/aether#54]
Hi, 

I'm trying to get this theme set up with [Forestry CMS](https://forestry.io/), but it doesn't support page bundles. I'm trying to essentially roll back to this commit by filling in the changes: https://github.com/josephhutch/aether/commit/85960b6fa36c93c81d060c61b0e4bafaeb6fb631

However, that doesn't seem to be working. I'm new to editing these themes, but was wondering if you could help me figure this out.

Thanks,
Sebi

**Comment by josephhutch** [comment]
Hi Sebi, I would love to help.  What do you mean when you say the theme does not support page bundles?  The commit you referenced was when the theme improved page bundle support and that support has not changed since.  Is there something specific that isn't working?

**Comment by sebilozano** [comment]
Hi Joe -- thanks for the quick response. I meant that Forestry's CMS doesn't support page bundles/resources, which means it doesn't support Aether as of now. I'm trying to make Aether work without the use of page bundles and instead by referencing static/. Does that make sense?

**Comment by josephhutch** [comment]
Many changes following 85960b6 have used page bundle features.  I would roll back before that commit to revert all those changes.  You will loose the newer features but the theme should be compatible with Forestry.
