### ISSUE TITLE
bgimg not working

### ISSUE THREAD

**Issue by mukhtharcm** [josephhutch/aether#58]
# bgimg is set, but not working.
I Just copy pasted the whole exampleSite directory, but the background image is not showing.
I really loved this theme, but this thing is holding me back. 
dont take this as disturbance. 
Thank you.

**Comment by josephhutch** [comment]
You are correct, sorry about that.  This is fixed in d484fb73fcfc57a8fa6eef48954342a9725209f5.
Sometimes I change the theme and forget to update the exampleSite 😬

**Comment by mukhtharcm** [comment]
Thank you for fixing it 😄 🥳
