### ISSUE TITLE
Footer partial template not used anywhere

### ISSUE THREAD

**Issue by MaximilianKoestler** [josephhutch/aether#61]
An empty footer partial template exists at `layout/partials`, but it is not used anywhere, i.e. `{{ partial "footer.html" . }}` is not present in any of the templates.

According to my understanding, this makes adding a custom footer impossible without forking the whole theme.
Since `/layouts/partials/footer.html` is empty by default, it would not hurt using it in the site templates.

I am very new to all of Hugo and also its themes, so if I have missed a key concept here feel free to correct me.

**Comment by josephhutch** [comment]
Aether does not provide footer support as a design choice.  I can remove the footer partial to remove confusion but footer support is not planned.
