### ISSUE TITLE
Navigation menu broken when JavaScript is disabled

### ISSUE THREAD

**Issue by codeofdusk** [josephhutch/aether#67]
STR:

* Disable JavaScript (such as in about:config in Firefox)
* Open an Aether site
* Attempt to open the navigation menu

Expected behaviour: Navigation is somehow possible when JavaScript is disabled.

Actual behaviour: Internal navigation is impossible with JavaScript disabled.

**Comment by josephhutch** [comment]
Thank you for submitting an issue!  I have fixed this in #75.
