### ISSUE TITLE
Faceshot not shown

### ISSUE THREAD

**Issue by isaacdnew** [josephhutch/aether#69]
I'm just getting started with this theme, and I copied the example site into my site. Everything's working great, except that there's no card shown at the right of the blob (see screenshot below). faceshot.jpg is in assets/img/. Any ideas why this is happening?
![image](https://user-images.githubusercontent.com/13858215/146280742-10c12cdd-e4cf-450a-999c-7c598f32d354.png)

**Comment by heimoshuiyu** [comment]
Add

```
[params]
    headshotimg = "img/faceshot.jpg"
```

into `config.toml` and put image file under `/yourblog/assets/img/`

I think this is missing from the README.md

**Comment by isaacdnew** [comment]
Thanks so much—that fixed it! Probably a good idea to add that to the readme, then.

**Comment by josephhutch** [comment]
I've updated the README.  Sorry that this was missing.
