### ISSUE TITLE
Unable to create post because of unexpected key when processing archetypes.

### ISSUE THREAD

**Issue by N07070** [josephhutch/aether#7]
Hello.

First of all, thanks a lot for this theme, it's really beautiful. 

I've tried to use it and install it, but when I create a new post I get this error : 

```
ERROR: 2019/01/02 19:12:16 content.go:61: Error processing archetype file /home/user/blog/themes/aether/archetypes/post.md: yaml: line 1: did not find expected key
Error: yaml: line 1: did not find expected key
```

It seems to have been fixed by deleting the content of the Date and Title line of the __aether/archetypes/post.md__ file, leaving them blank upon generating the website.

I hope it will be fixed in future releases !

**Comment by josephhutch** [comment]
@N07070, can you paste the front matter for the post you are having trouble with?  I'd like to take a look at it and make sure everything is okay on my end.  I'm glad you like the theme!

**Comment by N07070** [comment]
I'm sorry, I don't understand what you mean by "the front matter" ?

You're welcome ! It's gonna be live soon.

**Comment by josephhutch** [comment]
For a post, the [Front Matter](https://gohugo.io/content-management/front-matter/) will look something like this
```
---
title: "Helloworld"
date: 2019-01-02T14:54:19-05:00
description: ""
categories: []
featuredImage: ""
dropCap: true
displayInMenu: false
displayInList: true
draft: true
---
```
Also, what version of Hugo are you using (`hugo version`)?

**Comment by N07070** [comment]
Indeed, I was using a very old version. I updated it and am now using the apt version.

I reverted my changes, and now all if working fine. Thanks for the help !
