### ISSUE TITLE
How do you change the home-blob-text and home-blob-title parameters? Maybe add a way in the config.toml file?

### ISSUE THREAD

**Issue by petitengineer** [josephhutch/aether#74]
Hello! I'm new to Hugo, so I apologize if this is a silly question. 😅

I was wondering how one goes about changing the blob title/text that goes beside the head shot. Is there any reason why parameters do not seem to exist in the config.toml for these two strings?

**Comment by josephhutch** [comment]
Hello 👋 
Please see the [Further Customization](https://github.com/josephhutch/aether#further-customization) section of the README.  I agree this could be implemented better.  I'll think it over.

**Comment by petitengineer** [comment]
Indeed, adding a file named "_index.md" to the content folder of the project with the following code works like a charm:
```
---
title: "This is the main heading text in big letters"
date: the date
description: "This is the subtext below the main heading in smaller letters"
---
```
If for whatever reason this does not work for someone, and you need **a temporary fix**, you can modify the following lines in the  home.html file in the layouts folder of the theme
```
{{ with .Title }}<h1 class="home-blob-title">{{ . | markdownify }}</h1>{{ end }}
{{ with .Description }}<p class="home-blob-text">{{ . }}</p>{{ end }} 
```
to
```
<h1 class="home-blob-title">Text</h1> 
<p class="home-blob-text">My text</p>
```
Though this is a **temporary fix**, and you should make a post regarding your specific problem.

Thanks for the help @josephhutch! 😅
