### ISSUE TITLE
Using local images for background does not work.

### ISSUE THREAD

**Issue by N07070** [josephhutch/aether#8]
The following does not work, maybe because it's a gif, maybe because it's a locally-hosted image ?

In config.toml
```
... 
homeimg = "/home/user/blog/static/img/background.gif"
bgimg = "/home/user/blog/static/img/background.gif"
...
```

Thanks for your work !

**Comment by josephhutch** [comment]
Image paths should are in respect to the root Hugo project directory.  In your case, I think you need `/img/background.gif`.

**Comment by N07070** [comment]
Indeed, perfect !
