### ISSUE TITLE
Remove calls to Google Services and host dynamic content locally.

### ISSUE THREAD

**Issue by N07070** [josephhutch/aether#9]
Currently, the theme comes bundled with calls to several websites, including some googleapis. They are mostly calls for javascript files that are used to render content.

It could improve performance and would improve privacy to have theses files locally hosted, and updated with the theme when needed, rather than serve third-party code to the website.

It was stated in the original blog post of aether :  

> Today’s web is a frustrating mess of pop-ups, intrusive banners, and ads obstructing the content. I designed aether to be free of all these distractions and simply highlight the content.

And indeed, they are no distractions, but the web of today is also about privacy, I think.

I can submit a patch to close this issue if needed.

**Comment by josephhutch** [comment]
@N07070 Sorry but I prefer to use CDNs to host these files for the better chance of a cache hit.
